client.println("<!DOCTYPE html>");
client.println("<html lang=\"ja\">");
client.println("<head>");
client.println("    <meta charset=\"UTF-8\">");
client.println("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
client.println("    <title>Local theater system</title>");
client.println("    <style>");
client.println("        body, html {");
client.println("            margin: 0;");
client.println("            padding: 0;");
client.println("            height: 100%;");
client.println("            justify-content: center;");
client.println("            align-items: center;");
client.println("            font-family: Arial, sans-serif;");
client.println("            background-color: #f0f0f0;");
client.println("        }");
client.println("");
client.println("        .container {");
client.println("            width: 100%;");
client.println("            padding: 50px 20px;");
client.println("            box-sizing: border-box;");
client.println("            display: flex;");
client.println("            flex-direction: column;");
client.println("            gap: 20px;");
client.println("            height: 90vh;");
client.println("        }");
client.println("");
client.println("        .header {");
client.println("            background-color: #ffffff;");
client.println("            border: 2px solid #e0e0e0;");
client.println("            border-radius: 10px;");
client.println("            padding: 20px;");
client.println("            display: flex;");
client.println("            flex-direction: column;");
client.println("            align-items: center;");
client.println("            margin-bottom: 20px;");
client.println("        }");
client.println("");
client.println("        .header-title {");
client.println("            font-size: 24px;");
client.println("            font-weight: bold;");
client.println("            margin-bottom: 15px;");
client.println("            color: #333;");
client.println("        }");
client.println("");
client.println("        .header-buttons {");
client.println("            display: flex;");
client.println("            gap: 20px;");
client.println("            width: 100%;");
client.println("            justify-content: center;");
client.println("        }");
client.println("");
client.println("        .button {");
client.println("            flex: 1;");
client.println("            display: flex;");
client.println("            justify-content: center;");
client.println("            align-items: center;");
client.println("            color: white;");
client.println("            border: none;");
client.println("            border-radius: 10px;");
client.println("            font-size: 18px;");
client.println("            cursor: pointer;");
client.println("            transition: background-color 0.3s ease;");
client.println("            text-decoration: none;");
client.println("            height: 65px;");
client.println("        }");
client.println("");
client.println("        .button {");
client.println("            background-color: #3498db;");
client.println("        }");
client.println("        .button:hover {");
client.println("            background-color: #2980b9;");
client.println("        }");
client.println("");
client.println("        .button-on {");
client.println("          background-image: url(\"/switch-on.png\");");
client.println("          background-repeat: no-repeat;");
client.println("          background-position: center;");
client.println("          background-size: 50px;");
client.println("        }");
client.println("        .button-off {");
client.println("          background-image: url(\"/switch-off.png\");");
client.println("          background-repeat: no-repeat;");
client.println("          background-position: center;");
client.println("          background-size: 50px;");
client.println("        }");
client.println("");
client.println("        /* カラーバリエーション */");
client.println("        .color1 {");
client.println("            background-color: #ff7a7a;");
client.println("        }");
client.println("        .color1:hover {");
client.println("            background-color: #ffbc7a;");
client.println("        }");
client.println("");
client.println("        .color2 {");
client.println("            background-color: #ff6666;");
client.println("        }");
client.println("        .color2:hover {");
client.println("            background-color: #ffb266;");
client.println("        }");
client.println("");
client.println("        .color3 {");
client.println("            background-color: #ff5151;");
client.println("        }");
client.println("        .color3:hover {");
client.println("            background-color: #ffa851;");
client.println("        }");
client.println("");
client.println("        .color4 {");
client.println("            background-color: #efefef;");
client.println("        }");
client.println("        .color4:hover {");
client.println("            background-color: #afafaf;");
client.println("        }");
client.println("");
client.println("    </style>");
client.println("    <script>");
client.println("      function changeVol(index) {");
client.println("        const table = {\"1\": \"/level0\", \"2\": \"/level1\", \"3\": \"/level2\"};");
client.println("        fetch(table[index]);");
client.println("      }");
client.println("      function execScene(enabled) {");
client.println("        fetch(enabled ? \"/theatreOn\" : \"/theatreOff\");");
client.println("      }");
client.println("    </script>");
client.println("</head>");
client.println("<body>");
client.println("    <div class=\"container\">");
client.println("        <div class=\"header\">");
client.println("            <div class=\"header-title\">Theater</div>");
client.println("            <div class=\"header-buttons\">");
client.println("                <button class=\"button color4 button-on\" onclick=\"execScene(true)\"></button>");
client.println("                <button class=\"button color4 button-off\" onclick=\"execScene(false)\"></button>");
client.println("            </div>");
client.println("        </div>");
client.println("");
client.println("        <button class=\"button color1\" onclick=\"changeVol(1)\">Level 1</button>");
client.println("        <button class=\"button color2\" onclick=\"changeVol(2)\">Level 2</button>");
client.println("        <button class=\"button color3\" onclick=\"changeVol(3)\">Level 3</button>");
client.println("    </div>");
client.println("</body>");
client.println("</html>");
